### ISSUE TITLE
Compatibility with pg-query-stream 3

### ISSUE THREAD

**Issue by daveisfera** [vitaly-t/pg-promise#695]
### Expected behavior
`pg-query-stream` 3 can be used with `pg-promise` (see [here](https://github.com/brianc/node-postgres/blob/master/CHANGELOG.md#pg-query-stream300)

### Actual behavior
It errors out:
```
TypeError: stream.close is not a function
    at PgQueryStream.onError (/usr/src/app/node_modules/pg-promise/lib/stream.js:78:16)
    at PgQueryStream.emit (events.js:223:5)
    at PgQueryStream.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[nodemon] app crashed - waiting for file changes before starting...
```

### Steps to reproduce
Run `db.stream()` with `pg-query-stream` 3

### Environment

* Version of pg-promise: 10.3.5
* OS type (Linux/Windows/Mac): Alpine 3.11
* Version of Node.js: 12.14.1

**Comment by vitaly-t** [comment]
It is a known issue. Only v2.x is supported. Currently, v3.x only works with [10.4.0-Beta.3](https://github.com/vitaly-t/pg-promise/releases/tag/10.4.0-beta.3).

**Comment by daveisfera** [comment]
👍 thanks for the quick response

**Comment by vitaly-t** [comment]
[Release 10.4.0](https://github.com/vitaly-t/pg-promise/releases/tag/10.4.0) now requires `pg-query-stream` v3.0.0 or newer.

**Comment by Maulik3110** [comment]
How to use pg-query-stream with pg-promise?
can you provide any example link? It will be big help for me

**Comment by vitaly-t** [comment]
@Maulik3110 [It is in Wiki](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#streaming).
