### ISSUE TITLE
Type is incorrect for tx function? 

### ISSUE THREAD

**Issue by OrKoN** [vitaly-t/pg-promise#503]
### Expected behavior

The following compiles in TS 2.8.1 (taken from here http://vitaly-t.github.io/pg-promise/txMode.TransactionMode.html)

```
const TransactionMode = pgp.txMode.TransactionMode;
const isolationLevel = pgp.txMode.isolationLevel;

// Create a reusable transaction mode (serializable + read-only + deferrable):
const mode = new TransactionMode({
    tiLevel: isolationLevel.serializable,
    readOnly: true,
    deferrable: true
});

db.tx({mode}, t => {
    return t.any('SELECT * FROM table');
})
    .then(data => {
        // success;
    })
    .catch(error => {
        // error
    });
```

### Actual behavior

```
db.ts(185,7): error TS2345: Argument of type '{ mode: TransactionMode; }' is not assignable to parameter of type '{ tag?: any; mode?: ITXMode | undefined; }'.
  Types of property 'mode' are incompatible.
    Type 'TransactionMode' is not assignable to type 'ITXMode | undefined'.
      Type 'TransactionMode' is not assignable to type 'ITXMode'.
        Property 'isolationLevel' is missing in type 'TransactionMode'.
```

### Steps to reproduce

1. Compile the snippet with TS
2. It seems like here https://github.com/vitaly-t/pg-promise/blob/master/typescript/pg-promise.d.ts#L482 it should be Transaction mode instead of ITXMode

### Environment

* Version of pg-promise: 8.2.2
* OS type Linux/Windows/Mac: Mac
* Version of Node.js: v8.11.1

**Comment by vitaly-t** [comment]
Interesting,... I will have a look later this evening.

**Comment by vitaly-t** [comment]
Fixed in [v8.2.3](https://github.com/vitaly-t/pg-promise/releases/tag/v.8.2.3).

**Comment by OrKoN** [comment]
Thanks for the quick fix! I will upgrade soon
